name: Import Publications

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install academic CLI
        run: pip install academic

      - name: Import publications from BibTeX
        run: academic import publications.bib content/publication/
