name: Import Publications

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: List files for debugging
        run: ls -R

      - name: Install Academic CLI
        run: |
          python -m pip install --upgrade pip
          pip install academic==0.10.0

      - name: Show BibTeX file
        run: cat publications.bib

      - name: Import publications
        run: academic import publications.bib content/publication/ --compact

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add content/publication/
          git commit -m "Add publications via Academic CLI" || echo "No changes to commit"
          git push