name: Import Publications

on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Debug file list
        run: ls -R

      - name: Install hugo-blox-import
        run: pip install hugo-blox-import

      - name: Show BibTeX file content
        run: cat publications.bib

      - name: Import publications from BibTeX
        run: hugo-blox-import publications.bib content/publication/

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add content/publication/
          git commit -m "Add publications via hugo-blox-import" || echo "No changes to commit"
          git push

